parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:flowtype/recommended
  - plugin:react/recommended
  - prettier
  - prettier/flowtype
  - prettier/react
plugins:
  - import
  - flowtype
  - react
  - prettier
rules:
  no-console: off
  import/order: error
  import/newline-after-import: error
  react/prop-types: off
  react/display-name: off
  prettier/prettier:
    - error
    -
      semi: false
      singleQuote: true
env:
  es6: true
  node: true
  jest: true
  browser: true
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
  import/resolver:
    babel-module:
      alias:
        ~: ./src
parserOptions:
  sourceType: module
  ecmaVersion: 2018
  ecmaFeatures:
    experimentalDecorators: true
    classes: true
    jsx: true
