---
  parser: babel-eslint
  extends:
    - plugin:react/recommended
    - plugin:import/recommended
    - plugin:jsx-a11y/recommended
    - prettier
    - prettier/react
  plugins:
    - node
    - promise
    - react
    - import
    - jsx-a11y
    - prettier
  env:
    es6: true
    node: true
    jest: true
    browser: true
  rules:
    react/prop-types: off
    prettier/prettier: error
  parserOptions:
    sourceType: module
    ecmaVersion: 2017
    ecmaFeatures:
      experimentalObjectRestSpread: true
      experimentalDecorators: true
      classes: true
      jsx: true
