parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - prettier
  - prettier/react
plugins:
  - react
  - jsx-a11y
  - import
  - prettier
rules:
  no-console: off
  react/prop-types: off
  react/display-name: off
  import/order: error
  prettier/prettier:
    - error
    -
      semi: false
      singleQuote: true
env:
  es6: true
  node: true
  jest: true
  browser: true
parserOptions:
  sourceType: module
  ecmaVersion: 2018
  ecmaFeatures:
    experimentalDecorators: true
    classes: true
    jsx: true
