---
  parser: babel-eslint
  extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:import/errors
    - plugin:import/warnings
    - plugin:jsx-a11y/recommended
    - prettier
    - prettier/react
  plugins:
    - react
    - import
    - jsx-a11y
    - prettier
  rules:
    no-console: off
    react/prop-types: off
    prettier/prettier: error
  env:
    es6: true
    node: true
    jest: true
    browser: true
  parserOptions:
    sourceType: module
    ecmaVersion: 2017
    ecmaFeatures:
      experimentalObjectRestSpread: true
      experimentalDecorators: true
      classes: true
      jsx: true
