---
parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - prettier
  - prettier/react
plugins:
  - react
  - jsx-a11y
  - prettier
rules:
  no-console: off
  react/prop-types: off
  import/order: error
  prettier/prettier:
    - error
    -
      singleQuote: true
      semi: false
      printWidth: 120
env:
  es6: true
  node: true
  jest: true
  browser: true
globals:
  fixture: true
parserOptions:
  sourceType: module
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
    experimentalDecorators: true
    classes: true
    jsx: true
