---
  syntax: scss
  extends:
    - stylelint-config-standard
    - stylelint-config-styled-components
  plugins:
    - stylelint-order
  rules:
    order/properties-alphabetical-order: true
  ignoreFiles:
    - src/worker.js