---
language: node_js
node_js:
  - "9.4.0"

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

dist: trusty
sudo: required

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - stty cols 80

script:
  - yarn run ci

notifications:
  email: false