version: 2

jobs:
  bootstrap:
    docker:
      - image: circleci/node:9.4.0
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Install package
          command: yarn install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/node:9.4.0
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Run code lint
          command: yarn run lint
  acceptance:
    docker:
      - image: circleci/node:9.4.0-browsers
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Run e2e test
          command: yarn run test:e2e
  deploy:
    docker:
      - image: circleci/node:9.4.0
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            git config --global user.name ymkz
            git config --global user.email ymkzly@gmail.com
            git commit --allow-empty -m "release#${CIRCLE_BUILD_NUM} (Circle CI)[ci skip]"
            git push git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH}:release

workflows:
  version: 2
  workflow:
    jobs:
      - bootstrap
      - lint:
          requires:
            - bootstrap
      - acceptance:
          requires:
            - bootstrap
            - lint
      - deploy:
          requires:
            - bootstrap
            - lint
            - acceptance
          filters:
            branches:
              only: master
