version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.9.0@sha256:f08acb30cef8d8077e7b5f912092b40e390d67de845ce09f36bc818d741b5c04
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "yarn.lock" }}
          - dependencies-
      - run:
          name: Install packages
          command: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Unit Test
          command: CI=true yarn run test:cov && yarn run codecov
