---
version: 2
jobs:
  bootstrap:
    docker:
      - image: circleci/node:9.4.0-browsers
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Install package
          command: yarn install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run code lint
          command: yarn run lint
      - run:
          name: Run e2e test
          command: yarn run test:e2e
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Deploy
          command: yarn run deploy
