version: 2.1
orbs:
  cypress: cypress-io/cypress@1.5.1
executors:
  default:
    working_directory: ~/app
    docker:
      - image: circleci/node:11
        environment:
          HUSKY_SKIP_INSTALL: true
commands:
  restore_dependencies:
    steps:
      - restore_cache:
          name: Restore node_modules
          key: app-deps-{{ checksum "package-lock.json" }}
  save_dependencies:
    steps:
      - save_cache:
          name: Cache node_modules
          key: app-deps-{{ checksum "package-lock.json" }}
          paths: ~/app/node_modules
jobs:
  setup:
    executor: default
    steps:
      - checkout
      - restore_dependencies
      - run:
          name: Install dependencies
          command: npm install
      - save_dependencies
  check:
    executor: default
    steps:
      - checkout
      - restore_dependencies
      - run:
          name: Run Lint
          command: npm run lint
      - run:
          name: Run Typecheck
          command: npm run typecheck
      - run:
          name: Run Unit Test
          command: npm run coverage && npm run codecov
workflows:
  work:
    jobs:
      - setup
      - check:
          requires:
            - setup
      - cypress/install:
          requires:
            - setup
          executor: cypress/browsers-chrome69
      - cypress/run:
          requires:
            - cypress/install
          executor: cypress/browsers-chrome69
          build: npm run build
          start: npm run start
          command: npm run percy exec -- cypress run --browser chrome --record
