version: 2

jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:11-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          command: yarn lint
      - run:
          command: yarn typecheck
      - run:
          command: yarn test
