version: 2.1

description: A continuous integration for website about ymkz.

commands:
  install:
    steps:
      - run: yarn install
  lint:
    steps:
      - run: yarn run lint
  typecheck:
    steps:
      - run: yarn run typecheck
  test:
    steps:
      - run: yarn run test

executors:
  default:
    docker:
      - image: circleci/node:11-browsers

jobs:
  hello-build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - lint
      - typecheck
      - test
