version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.9.0
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "yarn.lock" }}
          - dependencies-
      - run:
          name: Install packages
          command: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Lint code
          command: yarn run lint
      - run:
          name: Unit test code
          command: CI=true yarn run test
