---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4.0-browsers
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ .Environment.CACHE_KEY }}-{{ checksum "yarn.lock" }}
          - yarn-{{ .Environment.CACHE_KEY }}-
      - run:
          name: Install package
          command: yarn install
      - save_cache:
          key: yarn-{{ .Environment.CACHE_KEY }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run code lint
          command: yarn run ci
      - store_test_results:
          path: /tmp/e2e