version: 2

jobs:
  bootstrap:
    docker:
      - image: circleci/node:9.4.0
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Install package
          command: yarn install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/node:9.4.0
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Run code lint
          command: yarn run lint
  e2e:
    docker:
      - image: circleci/node:9.4.0-browsers
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Run e2e test
          command: yarn run e2e
  deploy:
    docker:
      - image: circleci/node:9.4.0
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Deploy
          command: yarn run netlify deploy --path build --env production --site-id ${SITE_ID} --access-token ${ACCESS_TOKEN}

workflows:
  version: 2
  workflow:
    jobs:
      - bootstrap
      - lint:
          requires:
            - bootstrap
      - e2e:
          requires:
            - bootstrap
            - lint
      - deploy:
          requires:
            - bootstrap
            - lint
            - e2e
          filters:
            branches:
              only: master
