version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:11-browsers
        environment:
          HUSKY_SKIP_INSTALL: true
    working_directory: ~/app
jobs:
  checkout_code:
    executor: default
    steps:
      - checkout
      - save_cache:
          key: app-code-{{ .Environment.CIRCLE_SHA1 }}
          paths: ~/app
  install_dependencies:
    executor: default
    steps:
      - restore_cache:
          key: app-code-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: app-deps-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: app-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  check_code:
    executor: default
    steps:
      - restore_cache:
          key: app-code-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: app-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Typecheck
          command: yarn run typecheck
  build_code:
    executor: default
    steps:
      - restore_cache:
          key: app-code-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: app-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: yarn run build
workflows:
  version: 2
  test:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - check_code:
          requires:
            - install_dependencies
      - biuld_code:
          requires:
            - install_dependencies
