defaults: &defaults
  docker:
    - image: circleci/node:9.4.0-browsers
  working_directory: ~/workspace

version: 2

jobs:
  bootstrap:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Install package
          command: yarn install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  coverage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Run coverage check
          command: yarn run coverage:coveralls
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Run code lint
          command: yarn run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Run unit test
          command: yarn run test
  e2e:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Run e2e test
          command: yarn run e2e
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Build
          command: yarn run build
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - build
  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Deploy
          command: yarn run netlify deploy --path build --env production --site-id ${SITE_ID} --access-token ${ACCESS_TOKEN}

workflows:
  version: 2
  workflow:
    jobs:
      - bootstrap
      - coverage
          requires:
            - bootstrap
      - lint:
          requires:
            - bootstrap
      - test:
          requires:
            - bootstrap
            - lint
      - e2e:
          requires:
            - bootstrap
            - lint
      - build:
          requires:
            - bootstrap
            - lint
            - test
            - e2e
      - deploy:
          requires:
            - bootstrap
            - lint
            - test
            - e2e
            - build
          filters:
            branches:
              only: master
