version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1@sha256:bef30ea34ef5c7e402bd53be0b3830dad705898f0ed0670d046464ed704302a2
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "yarn.lock" }}
          - dependencies-
      - run:
          name: Install packages
          command: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: CI=true yarn run lint
      # - run:
      #     name: Unit Test
      #     command: CI=true yarn run test:cov && yarn run codecov
