version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:11-browsers

commands:
  install:
    steps:
      - run: yarn install
  lint:
    steps:
      - run: yarn run lint
  typecheck:
    steps:
      - run: yarn run typecheck
  test:
    steps:
      - run: yarn run test

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - lint
      - typecheck
      - test

workflows:
  normal:
    jobs:
      - build
