version: 2
jobs:
  bootstrap:
    docker:
      - image: circleci/node:9.4.0
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Install package
          command: yarn install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/node:9.4.0
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Run code lint
          command: yarn run lint
  acceptance:
    docker:
      - image: circleci/node:9.4.0-browsers
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Run e2e test
          command: yarn run test:e2e
  build:
    docker:
      - image: circleci/node:9.4.0
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Build
          command: yarn run build
  deploy:
    docker:
      - image: circleci/node:9.4.0
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run:
          name: Deploy
          command: yarn run deploy

workflows:
  version: 2
  workflow:
    jobs:
      - bootstrap
      - lint:
          requires:
            - bootstrap
      - acceptance:
          requires:
            - bootstrap
            - lint
      - build:
          requires:
            - bootstrap
            - lint
            - acceptance
      - deploy:
          requires:
            - bootstrap
            - lint
            - acceptance
            - build
          filters:
            branches:
              only: master
